### ISSUE TITLE
你好，请问这个项目要用什么软件打开？

### ISSUE THREAD

**Issue by xukai777** [shohoku3/Ubandi#1]

**Comment by shohoku3** [comment]
需要node环境

**Comment by shohoku3** [comment]
这个项目我只放了原型图和框架的代码在上面 没有具体的业务代码

**Comment by xukai777** [comment]
不能用eclipse运行吗

**Comment by shohoku3** [comment]
eclipse可以打开 但是需要其他的依赖环境

**Comment by xukai777** [comment]
老哥可以提供下源码吗？完全没有头绪啊。

**Comment by shohoku3** [comment]
你做毕设莫

**Comment by xukai777** [comment]
学年设计

**Comment by shohoku3** [comment]
我这里没有源码只有这个项目的原型图

**Comment by shohoku3** [comment]
我朋友可能源码还在

**Comment by xukai777** [comment]
老哥啥时候更新下代码呗，嘻嘻

**Comment by xukai777** [comment]
老哥，可以给个好友位吗？

**Comment by shohoku3** [comment]
加我微信吧 2812845017<tel:2812845017>



发自我的小米手机
在 xukai777 <notifications@github.com>，2019年5月12日 09:38写道：

老哥，可以给个好友位吗？

**Comment by shohoku3** [comment]
syf2812845017<tel:2812845017> 这个是微信



发自我的小米手机
在 xukai777 <notifications@github.com>，2019年5月12日 09:38写道：

老哥，可以给个好友位吗？
